// Generated by scripts/apply-waitlist.py from scripts/waitlist-i18n.json. Edit the JSON, not this file.
export const WAITLIST_MAIL = {
  "en": {
    "mailSubject": "You’re on the list: Control My Mac for {platforms}",
    "mailBoth": "Windows and Android",
    "mailHello": "Thanks for signing up.",
    "mailIntro": "This email confirms that your address works. I’ll email you the day Control My Mac for {platforms} is released.",
    "mailSpam": "Did this email land in your spam or junk folder? Please move it to your inbox, or mark it as “not spam”. Otherwise the release email may never reach you.",
    "mailNews": "You also asked for Sebastian Apps news: occasional app news and promo codes. Every one of those emails has an unsubscribe link.",
    "mailLeave": "Didn’t sign up, or changed your mind? Reply to this email and I’ll remove you.",
    "mailCountry": "Slovenia",
    "mailPrivacy": "Privacy Policy"
  },
  "de": {
    "mailSubject": "Du bist auf der Liste: Control My Mac für {platforms}",
    "mailBoth": "Windows und Android",
    "mailHello": "Danke für deine Anmeldung.",
    "mailIntro": "Diese E-Mail bestätigt, dass deine Adresse funktioniert. Ich schreibe dir am Tag der Veröffentlichung von Control My Mac für {platforms}.",
    "mailSpam": "Ist diese E-Mail in deinem Spam- oder Junk-Ordner gelandet? Bitte verschiebe sie in deinen Posteingang oder markiere sie als „kein Spam“. Sonst erreicht dich die E-Mail zur Veröffentlichung womöglich nie.",
    "mailNews": "Du hast außerdem Neuigkeiten von Sebastian Apps gewünscht: gelegentliche App-Neuigkeiten und Aktionscodes. Jede dieser E-Mails enthält einen Abmeldelink.",
    "mailLeave": "Du hast dich nicht angemeldet oder es dir anders überlegt? Antworte auf diese E-Mail, dann trage ich dich aus.",
    "mailCountry": "Slowenien",
    "mailPrivacy": "Datenschutzerklärung"
  },
  "es": {
    "mailSubject": "Ya estás en la lista: Control My Mac para {platforms}",
    "mailBoth": "Windows y Android",
    "mailHello": "Gracias por apuntarte.",
    "mailIntro": "Este correo confirma que tu dirección funciona. Te escribiré el día que salga Control My Mac para {platforms}.",
    "mailSpam": "¿Ha llegado este correo a tu carpeta de spam o correo no deseado? Muévelo a tu bandeja de entrada o márcalo como «no es spam». Si no, puede que el correo del lanzamiento no te llegue nunca.",
    "mailNews": "También pediste novedades de Sebastian Apps: novedades de apps y códigos promocionales de vez en cuando. Todos esos correos incluyen un enlace para darte de baja.",
    "mailLeave": "¿No te apuntaste tú o has cambiado de opinión? Responde a este correo y te borro de la lista.",
    "mailCountry": "Eslovenia",
    "mailPrivacy": "Política de privacidad"
  },
  "fr": {
    "mailSubject": "Vous êtes sur la liste : Control My Mac pour {platforms}",
    "mailBoth": "Windows et Android",
    "mailHello": "Merci de votre inscription.",
    "mailIntro": "Cet e-mail confirme que votre adresse fonctionne. Je vous écrirai le jour de la sortie de Control My Mac pour {platforms}.",
    "mailSpam": "Cet e-mail est-il arrivé dans vos courriers indésirables ? Déplacez-le dans votre boîte de réception ou marquez-le comme « pas un spam ». Sinon, l’e-mail de sortie risque de ne jamais vous parvenir.",
    "mailNews": "Vous avez aussi demandé les nouvelles de Sebastian Apps : des nouvelles d’apps et des codes promo de temps en temps. Chacun de ces e-mails contient un lien de désabonnement.",
    "mailLeave": "Cette inscription n’est pas de vous, ou vous avez changé d’avis ? Répondez à cet e-mail et je vous retirerai de la liste.",
    "mailCountry": "Slovénie",
    "mailPrivacy": "Politique de confidentialité"
  },
  "it": {
    "mailSubject": "Sei in lista: Control My Mac per {platforms}",
    "mailBoth": "Windows e Android",
    "mailHello": "Grazie per l’iscrizione.",
    "mailIntro": "Questa email conferma che il tuo indirizzo funziona. Ti scriverò il giorno in cui uscirà Control My Mac per {platforms}.",
    "mailSpam": "Questa email è finita nello spam o nella posta indesiderata? Spostala nella posta in arrivo o segnalala come «non spam». Altrimenti l’email sull’uscita potrebbe non raggiungerti mai.",
    "mailNews": "Hai chiesto anche le novità di Sebastian Apps: novità sulle app e codici promozionali ogni tanto. Ogni email di questo tipo contiene un link per disiscriverti.",
    "mailLeave": "Non hai richiesto l’iscrizione o hai cambiato idea? Rispondi a questa email e ti rimuovo dalla lista.",
    "mailCountry": "Slovenia",
    "mailPrivacy": "Informativa sulla privacy"
  },
  "nl": {
    "mailSubject": "Je staat op de lijst: Control My Mac voor {platforms}",
    "mailBoth": "Windows en Android",
    "mailHello": "Bedankt voor je aanmelding.",
    "mailIntro": "Deze e-mail bevestigt dat je adres werkt. Ik mail je op de dag dat Control My Mac voor {platforms} uitkomt.",
    "mailSpam": "Is deze e-mail in je spam- of ongewenste-mailmap terechtgekomen? Verplaats hem dan naar je inbox of markeer hem als “geen spam”. Anders komt de releasemail misschien nooit bij je aan.",
    "mailNews": "Je hebt ook nieuws van Sebastian Apps aangevraagd: af en toe app-nieuws en promocodes. Elke e-mail daarvan bevat een afmeldlink.",
    "mailLeave": "Heb je je niet aangemeld of ben je van gedachten veranderd? Reageer op deze e-mail, dan haal ik je van de lijst.",
    "mailCountry": "Slovenië",
    "mailPrivacy": "Privacybeleid"
  },
  "pl": {
    "mailSubject": "Jesteś na liście: Control My Mac na {platforms}",
    "mailBoth": "Windows i Android",
    "mailHello": "Dziękuję za zapisanie się.",
    "mailIntro": "Ten e-mail potwierdza, że Twój adres działa. Napiszę do Ciebie w dniu premiery Control My Mac na {platforms}.",
    "mailSpam": "Czy ten e-mail trafił do folderu ze spamem? Przenieś go do skrzynki odbiorczej albo oznacz jako „nie spam”. W przeciwnym razie e-mail o premierze może nigdy do Ciebie nie dotrzeć.",
    "mailNews": "Zaznaczona została też opcja nowości Sebastian Apps: od czasu do czasu wiadomości o aplikacjach i kody promocyjne. Każdy taki e-mail zawiera link do wypisania się.",
    "mailLeave": "Ten zapis to pomyłka albo zmieniasz zdanie? Odpisz na ten e-mail, a usunę Cię z listy.",
    "mailCountry": "Słowenia",
    "mailPrivacy": "Polityka prywatności"
  },
  "pt": {
    "mailSubject": "Você está na lista: Control My Mac para {platforms}",
    "mailBoth": "Windows e Android",
    "mailHello": "Obrigado por se inscrever.",
    "mailIntro": "Este e-mail confirma que seu endereço funciona. Vou escrever para você no dia em que o Control My Mac para {platforms} for lançado.",
    "mailSpam": "Este e-mail caiu na sua pasta de spam ou lixo eletrônico? Mova-o para a caixa de entrada ou marque como “não é spam”. Caso contrário, o e-mail do lançamento pode nunca chegar até você.",
    "mailNews": "Você também pediu as novidades da Sebastian Apps: novidades de apps e códigos promocionais de vez em quando. Todo e-mail desse tipo tem um link para cancelar a inscrição.",
    "mailLeave": "Não se inscreveu ou mudou de ideia? Responda a este e-mail e eu removo você da lista.",
    "mailCountry": "Eslovênia",
    "mailPrivacy": "Política de Privacidade"
  },
  "ru": {
    "mailSubject": "Вы в списке: Control My Mac для {platforms}",
    "mailBoth": "Windows и Android",
    "mailHello": "Спасибо, что подписались.",
    "mailIntro": "Это письмо подтверждает, что ваш адрес работает. Я напишу вам в день выхода Control My Mac для {platforms}.",
    "mailSpam": "Это письмо попало в папку «Спам» или «Нежелательная почта»? Переместите его во входящие или отметьте как «не спам». Иначе письмо о выходе может до вас не дойти.",
    "mailNews": "Вы также попросили новости Sebastian Apps: иногда новости приложений и промокоды. В каждом таком письме есть ссылка для отписки.",
    "mailLeave": "Не подписывались или передумали? Ответьте на это письмо, и я удалю вас из списка.",
    "mailCountry": "Словения",
    "mailPrivacy": "Политика конфиденциальности"
  },
  "sl": {
    "mailSubject": "Na seznamu ste: Control My Mac za {platforms}",
    "mailBoth": "Windows in Android",
    "mailHello": "Hvala za prijavo.",
    "mailIntro": "To sporočilo potrjuje, da vaš naslov deluje. Pisal vam bom na dan izida aplikacije Control My Mac za {platforms}.",
    "mailSpam": "Je to sporočilo pristalo v mapi z vsiljeno pošto? Premaknite ga v prejeto pošto ali ga označite kot „ni vsiljena pošta“. Sicer vas sporočilo o izidu morda nikoli ne bo doseglo.",
    "mailNews": "Zahtevali ste tudi novice Sebastian Apps: občasne novice o aplikacijah in promocijske kode. Vsako takšno sporočilo vsebuje povezavo za odjavo.",
    "mailLeave": "Se niste prijavili ali ste si premislili? Odgovorite na to sporočilo in vas bom odstranil.",
    "mailCountry": "Slovenija",
    "mailPrivacy": "Pravilnik o zasebnosti"
  },
  "tr": {
    "mailSubject": "Listedesin: {platforms} için Control My Mac",
    "mailBoth": "Windows ve Android",
    "mailHello": "Kaydolduğun için teşekkürler.",
    "mailIntro": "Bu e-posta, adresinin çalıştığını doğrular. {platforms} için Control My Mac’in çıktığı gün sana e-posta göndereceğim.",
    "mailSpam": "Bu e-posta spam veya gereksiz klasörüne mi düştü? Lütfen gelen kutuna taşı ya da “spam değil” olarak işaretle. Aksi halde çıkış e-postası sana hiç ulaşmayabilir.",
    "mailNews": "Ayrıca Sebastian Apps haberlerini de istedin: ara sıra uygulama haberleri ve promosyon kodları. Bu e-postaların her birinde abonelikten çıkma bağlantısı var.",
    "mailLeave": "Kaydolmadın mı ya da fikrini mi değiştirdin? Bu e-postayı yanıtla, seni listeden çıkarayım.",
    "mailCountry": "Slovenya",
    "mailPrivacy": "Gizlilik Politikası"
  },
  "uk": {
    "mailSubject": "Ви в списку: Control My Mac для {platforms}",
    "mailBoth": "Windows і Android",
    "mailHello": "Дякую, що підписалися.",
    "mailIntro": "Цей лист підтверджує, що ваша адреса працює. Я напишу вам у день виходу Control My Mac для {platforms}.",
    "mailSpam": "Цей лист потрапив у папку «Спам»? Перенесіть його до вхідних або позначте як «не спам». Інакше лист про вихід може до вас не дійти.",
    "mailNews": "Ви також попросили новини Sebastian Apps: час від часу новини програм і промокоди. Кожен такий лист містить посилання для відписки.",
    "mailLeave": "Не підписувалися або передумали? Дайте відповідь на цей лист, і я видалю вас зі списку.",
    "mailCountry": "Словенія",
    "mailPrivacy": "Політика приватності"
  },
  "ja": {
    "mailSubject": "リストに登録しました：{platforms}向けControl My Mac",
    "mailBoth": "WindowsとAndroid",
    "mailHello": "ご登録ありがとうございます。",
    "mailIntro": "このメールは、メールアドレスが正しく届くことの確認です。{platforms}向けControl My Macを公開する日に、メールでお知らせします。",
    "mailSpam": "このメールは迷惑メールフォルダに入っていませんでしたか？受信トレイに移すか、「迷惑メールではない」と設定してください。そうしないと、公開のお知らせメールが届かない可能性があります。",
    "mailNews": "Sebastian Appsのお知らせもご希望いただきました。アプリのお知らせやプロモーションコードを、ときどきお送りします。これらのメールにはすべて配信停止リンクがあります。",
    "mailLeave": "登録に心当たりがない場合や、気が変わった場合は、このメールに返信してください。リストから削除します。",
    "mailCountry": "スロベニア",
    "mailPrivacy": "プライバシーポリシー"
  },
  "ko": {
    "mailSubject": "명단에 등록되었습니다: {platforms}용 Control My Mac",
    "mailBoth": "Windows와 Android",
    "mailHello": "신청해 주셔서 감사합니다.",
    "mailIntro": "이 이메일은 주소가 정상적으로 작동하는지 확인하기 위한 것입니다. {platforms}용 Control My Mac이 출시되는 날 이메일로 알려 드리겠습니다.",
    "mailSpam": "이 이메일이 스팸함이나 정크 메일함에 들어 있었나요? 받은편지함으로 옮기거나 ‘스팸 아님’으로 표시해 주세요. 그러지 않으면 출시 안내 이메일이 도착하지 않을 수 있습니다.",
    "mailNews": "Sebastian Apps 소식도 신청하셨습니다. 앱 소식과 프로모션 코드를 가끔 보내 드립니다. 해당 이메일에는 모두 구독 취소 링크가 있습니다.",
    "mailLeave": "신청하신 적이 없거나 마음이 바뀌셨나요? 이 이메일에 답장해 주시면 명단에서 삭제해 드리겠습니다.",
    "mailCountry": "슬로베니아",
    "mailPrivacy": "개인정보 처리방침"
  },
  "zh": {
    "mailSubject": "你已在名单中：Control My Mac {platforms} 版",
    "mailBoth": "Windows 和 Android",
    "mailHello": "感谢你的注册。",
    "mailIntro": "这封邮件用来确认你的邮箱地址可以正常收信。Control My Mac {platforms} 版发布的当天，我会给你发邮件。",
    "mailSpam": "这封邮件是不是进了垃圾邮件文件夹？请把它移到收件箱，或标记为“不是垃圾邮件”。否则发布通知邮件可能永远无法送达你。",
    "mailNews": "你还选择了接收 Sebastian Apps 的新闻：偶尔的应用新闻和优惠代码。每封这类邮件都带有退订链接。",
    "mailLeave": "没有注册过，或者改变主意了？回复这封邮件，我会把你从名单中删除。",
    "mailCountry": "斯洛文尼亚",
    "mailPrivacy": "隐私政策"
  },
  "zh-hant": {
    "mailSubject": "你已加入名單：Control My Mac {platforms} 版",
    "mailBoth": "Windows 和 Android",
    "mailHello": "感謝你的註冊。",
    "mailIntro": "這封郵件用來確認你的地址可以正常收信。Control My Mac {platforms} 版推出的當天，我會寄信通知你。",
    "mailSpam": "這封郵件是不是進了垃圾郵件匣？請把它移到收件匣，或標示為「不是垃圾郵件」。否則推出通知信可能永遠無法送達。",
    "mailNews": "你也選擇了接收 Sebastian Apps 的消息：不定期的 App 最新消息和優惠代碼。每封這類郵件都附有取消訂閱連結。",
    "mailLeave": "沒有註冊過，或改變心意了？回覆這封郵件，我就會把你從名單中刪除。",
    "mailCountry": "斯洛維尼亞",
    "mailPrivacy": "隱私權政策"
  }
};
