"""Content for scripts/build-grid-guides.py. Shortcut lists are the vendors' DEFAULT macOS shortcuts, checked against
their official documentation in September 2026 (links in each page's source_note)."""

TM_ELGATO = ""  # the footer already carries the Elgato / Stream Deck note

MACRO = {
    "path": "/macro-pad-for-mac",
    "crumb": "Macro pad for Mac",
    "title": "Use Your iPhone as a Macro Pad for Mac | Control My Mac",
    "desc": "Turn your iPhone or iPad into a macro pad for your Mac: one-tap buttons for any shortcut, with a Grid for every app that switches in by itself.",
    "og": "Your iPhone as a macro pad for your Mac",
    "pill": "One tap for any Mac shortcut",
    "h1": 'Use your iPhone as a <span class="grad">macro pad</span> for your Mac.',
    "sub": "A macro pad is a small board of extra keys, each one firing a shortcut you'd otherwise have to finger-twist on the keyboard. Control My Mac turns the iPhone or iPad you already own into one: a Grid of one-tap buttons for any Mac shortcut, with its own Grid for every Mac app, switching in by itself.",
    "grid_h2": "A starter Grid that works in every app",
    "grid_lead": "These are standard macOS shortcuts, so they work whatever app is in front. Make them your Default grid, then give your busiest apps a Grid of their own.",
    "buttons": [
        ("Screenshot", "Shift-Command-4", "Capture a part of the screen you select"),
        ("Screen tools", "Shift-Command-5", "Open the screenshot and screen recording toolbar"),
        ("Spotlight", "Command-Space", "Search apps, files and more"),
        ("Mission Control", "Control-Up Arrow", "See every open window and Space"),
        ("Emoji", "Control-Command-Space", "Open the emoji and symbols picker"),
        ("Undo", "Command-Z", "Undo the last action"),
        ("Redo", "Shift-Command-Z", "Redo it again"),
        ("Hide app", "Command-H", "Hide the app that's in front"),
        ("Full screen", "Control-Command-F", "Toggle full screen, in apps that support it"),
        ("Force Quit", "Option-Command-Esc", "Open the Force Quit window"),
        ("Lock Screen", "Control-Command-Q", "Lock your Mac right away"),
        ("Close window", "Command-W", "Close the front window"),
    ],
    "source_note": 'Default shortcuts from Apple\'s <a href="https://support.apple.com/en-us/102650">Mac keyboard shortcuts</a> page, checked September 2026. Some depend on your macOS settings; if one does nothing, record it from your Mac instead.',
    "steps_h2": "Set it up in a minute",
    "steps_lead": "You need the free Mac app and Control My Mac on your iPhone or iPad. Pairing is one QR scan, then:",
    "steps": [
        ("Open the Grid", "Tap Grid at the bottom of the app. The grid you see first is Default, the one every app uses unless it has its own."),
        ("Add a button", "Tap Edit Grid and add a button. Press the shortcut on your Mac's keyboard to record it, or pick the keys by hand. A button can also send a few shortcuts back to back."),
        ("Name it and place it", "Give it a short label, then drag it to where your thumb rests. Pick how many rows and columns the Grid has."),
        ("Give busy apps their own Grid", "With an app in front on your Mac, tap “Grid for” and that app's name. Its Grid switches in by itself whenever that app is in front. See the <a href=\"/premiere-pro-shortcuts-iphone\">Premiere Pro</a>, <a href=\"/davinci-resolve-shortcuts-iphone\">DaVinci Resolve</a> and <a href=\"/final-cut-pro-shortcuts-iphone\">Final Cut Pro</a> guides for ready-made examples."),
    ],
    "shots": ["zoom", "menu"],
    "honest": """        <p><strong>What “macro” means here.</strong> Each button sends a keyboard shortcut, or a few in a row, to your Mac. It doesn't type text snippets, run scripts or wait between steps. If a key combo can do it on your Mac, a button can too.</p>
        <p><strong>Full App.</strong> A Grid for each Mac app and Auto-Switch are part of Full App ($3.99 a month or $17.99 once in the US, with a 7-day free trial). The free Essentials plan includes one Grid button, so you can try the idea first.</p>
        <p><strong>Learning from the Mac.</strong> Recording a shortcut by pressing it on the Mac needs the Input Monitoring permission for the Mac app. It only listens while you're recording and saves just the combo. You can also set every shortcut by hand.</p>
        <p><strong>More than buttons.</strong> The same app is also a trackpad, a keyboard and a launcher for apps and windows, all built to be used with one finger. More in the <a href="/iphone-as-mouse-for-mac">iPhone as a mouse guide</a>.</p>""",
    "faq": [
        ("Can an iPhone be a macro pad for a Mac?",
         "Yes, with an app. Control My Mac turns an iPhone or iPad into a Grid of one-tap buttons that send keyboard shortcuts to your Mac over Bluetooth or Wi-Fi. You need the free Mac companion app."),
        ("Do I need to buy a hardware macro pad?",
         "Not if your buttons are mostly keyboard shortcuts. A hardware pad is better if you want to press keys by feel without looking, or need knobs and dials."),
        ("Can the buttons change depending on the app?",
         "Yes. Every Mac app can get its own Grid, made in one tap, that switches in by itself when that app is in front. Every other app uses your Default grid. This is part of Full App."),
        ("Does it work with Windows?",
         "No. Control My Mac is for Macs only (macOS 14 or later), on iPhone or iPad."),
    ],
    "final_h2": "Put a macro pad on the phone you own",
    "tm": "",
}

ADOBE_MAIN = "https://helpx.adobe.com/premiere/desktop/get-started/keyboard-shortcuts/default-keyboard-shortcuts.html"
PREMIERE = {
    "path": "/premiere-pro-shortcuts-iphone",
    "app": "Premiere Pro",
    "crumb": "Premiere Pro shortcuts",
    "title": "Premiere Pro Shortcut Deck on Your iPhone | Control My Mac",
    "desc": "A ready-made Grid of Premiere Pro shortcuts on your iPhone or iPad: Razor, Add Edit, Ripple Delete, markers and export, switching in with Premiere.",
    "og": "A Premiere Pro shortcut deck on the iPhone you already have",
    "pill": "Premiere in front, Premiere buttons on your phone",
    "h1": 'A <span class="grad">Premiere Pro</span> shortcut deck on your iPhone.',
    "sub": "Editing is a stream of small shortcuts: cut, trim, mark, cut again. Control My Mac puts them on a Grid of big one-tap buttons on your iPhone or iPad, and that Grid switches in by itself whenever Premiere is in front on your Mac. No extra hardware on the desk.",
    "grid_h2": "A starter Grid for Premiere Pro",
    "grid_lead": "Twelve buttons for a typical cutting session, using Premiere's default Mac shortcuts. Rename them, reorder them, or swap in the ones you use most.",
    "buttons": [
        ("Razor", "C", "Switch to the Razor tool"),
        ("Selection", "V", "Switch back to the Selection tool"),
        ("Add Edit", "Command-K", "Cut the targeted tracks at the playhead"),
        ("Add Edit, all tracks", "Shift-Command-K", "Cut every track at the playhead"),
        ("Ripple Delete", "Option-Delete", "Delete the selected clip and close the gap"),
        ("Trim start", "Q", "Ripple trim the start of the clip to the playhead"),
        ("Trim end", "W", "Ripple trim the end of the clip to the playhead"),
        ("Mark In", "I", "Set an In point"),
        ("Mark Out", "O", "Set an Out point"),
        ("Add Marker", "M", "Drop a marker at the playhead"),
        ("Transition", "Command-D", "Apply the default video transition"),
        ("Export", "Command-M", "Open Export"),
    ],
    "source_note": f'Default Mac shortcuts from Adobe\'s <a href="{ADOBE_MAIN}">Premiere keyboard shortcuts</a>, <a href="https://helpx.adobe.com/premiere/desktop/edit-projects/intro-to-editing/edit-video-in-premiere.html">editing</a> and <a href="https://helpx.adobe.com/ph_fil/premiere-pro/how-to/dynamic-trimming.html">trimming</a> help pages, checked September 2026. Ripple Delete is Option-Delete in the Timeline panel. Adobe now calls the app simply Premiere.',
    "steps_h2": "Set it up in a minute",
    "steps_lead": "You need the free Mac app and Control My Mac on your iPhone or iPad, paired once with a QR scan. Then:",
    "shots": ["premiere", "menu"],
    "faq": [
        ("Can I use my iPhone as a Stream Deck for Premiere Pro?",
         "For keyboard shortcuts, yes. Control My Mac gives Premiere its own Grid of one-tap buttons on your iPhone or iPad, and it switches in whenever Premiere is in front. It doesn't use Stream Deck plugins, so it sends shortcuts rather than plugin actions."),
        ("Does it work with the new Adobe Premiere?",
         "Yes. The Grid sends keyboard shortcuts, so it works with any version that uses them, including the app Adobe now calls Premiere."),
        ("What if I changed my Premiere shortcuts?",
         "Record each button by pressing your shortcut on the Mac, and the button sends exactly that. The table above uses Adobe's defaults."),
        ("Do I need an iPad?",
         "No. It works on iPhone. On iPad the Grid is bigger, with room for more buttons."),
    ],
    "final_h2": "Cut faster with the phone on your desk",
    "tm": "Adobe and Premiere are trademarks of Adobe. Control My Mac is not affiliated with Adobe.",
}

BMD = "https://documents.blackmagicdesign.com/UserManuals/DaVinci_Resolve_21_Reference_Manual.pdf"
RESOLVE = {
    "path": "/davinci-resolve-shortcuts-iphone",
    "app": "DaVinci Resolve",
    "crumb": "DaVinci Resolve shortcuts",
    "title": "DaVinci Resolve Shortcut Deck on Your iPhone | Control My Mac",
    "desc": "A ready-made Grid of DaVinci Resolve shortcuts on your iPhone or iPad: blade, split, ripple delete, marks and insert, switching in with Resolve.",
    "og": "A DaVinci Resolve shortcut deck on the iPhone you already have",
    "pill": "Resolve in front, Resolve buttons on your phone",
    "h1": 'A <span class="grad">DaVinci Resolve</span> shortcut deck on your iPhone.',
    "sub": "Resolve has a shortcut for almost everything, and some of them live on keys a MacBook barely has. Control My Mac puts the ones you use on a Grid of big one-tap buttons on your iPhone or iPad, and that Grid switches in by itself whenever Resolve is in front on your Mac.",
    "grid_h2": "A starter Grid for DaVinci Resolve",
    "grid_lead": "Twelve buttons for the Edit page, using Resolve's default Mac shortcuts. Keys like F9 to F11, the backslash and Forward Delete aren't in the phone's key picker yet, so record those by pressing them on your Mac.",
    "buttons": [
        ("Select", "A", "Selection mode"),
        ("Blade", "B", "Blade edit mode"),
        ("Split", "Command-\\", "Split the clip at the playhead"),
        ("Ripple Delete", "Forward Delete", "Delete and close the gap (fn-Delete on a MacBook)"),
        ("Mark In", "I", "Set an In point"),
        ("Mark Out", "O", "Set an Out point"),
        ("Marker", "M", "Add a marker"),
        ("Insert", "F9", "Insert the source clip"),
        ("Overwrite", "F10", "Overwrite with the source clip"),
        ("Replace", "F11", "Replace with the source clip"),
        ("Match Frame", "F", "Find the source frame"),
        ("Zoom to fit", "Shift-Z", "Show the whole timeline"),
    ],
    "source_note": f'Default Mac shortcuts from the <a href="{BMD}">DaVinci Resolve 21 Reference Manual</a> (Blackmagic Design, July 2026), checked September 2026. They work the same in the free version and in Studio.',
    "steps_h2": "Set it up in a minute",
    "steps_lead": "You need the free Mac app and Control My Mac on your iPhone or iPad, paired once with a QR scan. Then:",
    "shots": ["menu", "zoom"],
    "honest_extra": """
        <p><strong>Function keys.</strong> A button sends the real F9, F10 or F11 key, so there's no fn to hold. If F11 shows your desktop instead of replacing a clip, macOS is using F11 for Show Desktop: turn that off in System Settings, Keyboard, Keyboard Shortcuts, or give Replace a different key in Resolve.</p>""",
    "faq": [
        ("Can I use my iPhone as a Stream Deck for DaVinci Resolve?",
         "For keyboard shortcuts, yes. Control My Mac gives Resolve its own Grid of one-tap buttons on your iPhone or iPad, and it switches in whenever Resolve is in front. It doesn't replace a hardware panel with a jog wheel, like Blackmagic's own editor keyboards."),
        ("Does it work with the free version of Resolve?",
         "Yes. The Grid sends keyboard shortcuts, and they're the same in the free version and in Studio."),
        ("My MacBook has no F9 or Forward Delete key. Does that matter?",
         "No. A Grid button sends the key itself. To make the button, press the key once on your Mac while recording (fn-F9, or fn-Delete for Forward Delete) and it's saved."),
        ("What if I changed my Resolve shortcuts?",
         "Record each button by pressing your shortcut on the Mac, and the button sends exactly that. The table above uses Blackmagic's defaults."),
    ],
    "final_h2": "Edit with a deck you already own",
    "tm": "DaVinci Resolve is a trademark of Blackmagic Design. Control My Mac is not affiliated with Blackmagic Design.",
}

FCP_GUIDE = "https://support.apple.com/guide/final-cut-pro/keyboard-shortcuts-ver90ba5929/mac"
FCP = {
    "path": "/final-cut-pro-shortcuts-iphone",
    "app": "Final Cut Pro",
    "crumb": "Final Cut Pro shortcuts",
    "title": "Final Cut Pro Shortcut Deck on Your iPhone | Control My Mac",
    "desc": "A ready-made Grid of Final Cut Pro shortcuts on your iPhone or iPad: blade, connect, insert, append and share, switching in with Final Cut Pro.",
    "og": "A Final Cut Pro shortcut deck on the iPhone you already have",
    "pill": "Final Cut in front, Final Cut buttons on your phone",
    "h1": 'A <span class="grad">Final Cut Pro</span> shortcut deck on your iPhone.',
    "sub": "Final Cut Pro is built for the keyboard: blade, connect, insert, append, all a keystroke away. Control My Mac puts them on a Grid of big one-tap buttons on your iPhone or iPad, and that Grid switches in by itself whenever Final Cut Pro is in front on your Mac.",
    "grid_h2": "A starter Grid for Final Cut Pro",
    "grid_lead": "Twelve buttons for building a timeline, using Final Cut Pro's default Mac shortcuts. Rename them, reorder them, or swap in the ones you use most.",
    "buttons": [
        ("Blade", "Command-B", "Cut the clip at the playhead"),
        ("Blade All", "Shift-Command-B", "Cut every clip at the playhead"),
        ("Blade tool", "B", "Switch to the Blade tool"),
        ("Select tool", "A", "Switch back to the Select tool"),
        ("Range tool", "R", "Switch to the Range Selection tool"),
        ("Range start", "I", "Set the start of a range"),
        ("Range end", "O", "Set the end of a range"),
        ("Marker", "M", "Add a marker"),
        ("Connect", "Q", "Connect to the primary storyline"),
        ("Insert", "W", "Insert at the playhead"),
        ("Append", "E", "Append to the storyline"),
        ("Share", "Command-E", "Share to your default destination"),
    ],
    "source_note": f'Default Mac shortcuts from Apple\'s <a href="{FCP_GUIDE}">Final Cut Pro keyboard shortcuts</a> guide, checked September 2026.',
    "steps_h2": "Set it up in a minute",
    "steps_lead": "You need the free Mac app and Control My Mac on your iPhone or iPad, paired once with a QR scan. Then:",
    "shots": ["menu", "zoom"],
    "faq": [
        ("Can I control Final Cut Pro from my iPhone?",
         "Yes, through its keyboard shortcuts. Control My Mac gives Final Cut Pro its own Grid of one-tap buttons on your iPhone or iPad that switches in whenever Final Cut Pro is in front. The same app is also a trackpad and keyboard for everything else."),
        ("Is this the same as Final Cut Pro for iPad?",
         "No. Final Cut Pro for iPad is a separate editing app. Control My Mac is a remote for Final Cut Pro running on your Mac."),
        ("What if I changed my Final Cut Pro shortcuts?",
         "Record each button by pressing your shortcut on the Mac, and the button sends exactly that. The table above uses Apple's defaults."),
        ("Do I need an iPad?",
         "No. It works on iPhone. On iPad the Grid is bigger, with room for more buttons."),
    ],
    "final_h2": "Put Final Cut on a deck you already own",
    "tm": "Final Cut Pro is a trademark of Apple Inc.",
}

PAGES = [MACRO, PREMIERE, RESOLVE, FCP]
